# Basic
title: Iewoaix third home
subtitle: Personal blog
description: While there is life there is hope. 
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Iewoaix
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ä¿¡æ¯å®‰å…¨
url: "https://iewoaix.github.io"

# Comment
comment:
    # disqus: leopard
    duoshuo: Iewoaix

# Social
social:
    weibo: no 
    github: Iewoaix
    # twitter: 
    QQ: 1012097210 
# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 


# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Iewoaix'Blogs 

# Navigation buttons in the front page.s
nav:
    - {title: Archive, description: archive, url: '/archive'}   
    - {title: Tage, description: tags, url: '/tags'}      
    - {title: About me, description: about, url: '/about'}
    - {title: Friendship link, description: archive, url: '/links'}  
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


